In [2]:
#to import libraries
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
#to read dataset
df=pd.read_csv("C:/Users/Lenovo/Desktop/IITG (summer analytics)/hacktrain_with_features.csv")

df.head()

,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,20150125_N,...,20140218_N,20140202_N,20140117_N,20140101_N,mean_ndvi,min_ndvi,max_ndvi,range_ndvi,std_ndvi,class
0,637.5950,658.668,-1882.030,-1924.36,997.904,-1739.990,630.087,NaN,-1325.64,-944.084,...,211.328,-2203.020,-1180.19,433.906,-356.566818,-2203.02,997.904,3200.924,1310.703890,water
1,634.2400,593.705,-1625.790,-1672.32,914.198,-692.386,707.626,-1670.590,-1408.64,-989.285,...,220.878,-2250.000,-1360.56,524.075,-252.624381,-2250.00,914.198,3164.198,1167.751946,water
2,58.0174,-1599.160,NaN,-1052.63,NaN,-1564.630,NaN,729.790,-3162.14,NaN,...,369.214,-2202.120,NaN,-1343.550,-511.704400,-3162.14,952.178,4114.318,1569.573503,water
3,72.5180,NaN,380.436,-1256.93,515.805,-1413.180,-802.942,683.254,-2829.40,-1267.540,...,298.320,-2197.360,NaN,-826.727,-290.295917,-2829.40,1232.120,4061.520,1398.797808,water
4,1136.4400,NaN,NaN,1647.83,1935.800,NaN,2158.980,NaN,1242.87,-2646.050,...,1660.650,-116.801,-568.05,-1357.140,553.286190,-2646.05,2158.980,4805.030,1630.962942,water

In [4]:
df

,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,20150125_N,...,20140218_N,20140202_N,20140117_N,20140101_N,mean_ndvi,min_ndvi,max_ndvi,range_ndvi,std_ndvi,class
0,637.5950,658.668,-1882.030,-1924.36,997.904,-1739.990,630.087,NaN,-1325.640,-944.084,...,211.328,-2203.020,-1180.19,433.906,-356.566818,-2203.020,997.904,3200.924,1310.703890,water
1,634.2400,593.705,-1625.790,-1672.32,914.198,-692.386,707.626,-1670.590,-1408.640,-989.285,...,220.878,-2250.000,-1360.56,524.075,-252.624381,-2250.000,914.198,3164.198,1167.751946,water
2,58.0174,-1599.160,NaN,-1052.63,NaN,-1564.630,NaN,729.790,-3162.140,NaN,...,369.214,-2202.120,NaN,-1343.550,-511.704400,-3162.140,952.178,4114.318,1569.573503,water
3,72.5180,NaN,380.436,-1256.93,515.805,-1413.180,-802.942,683.254,-2829.400,-1267.540,...,298.320,-2197.360,NaN,-826.727,-290.295917,-2829.400,1232.120,4061.520,1398.797808,water
4,1136.4400,NaN,NaN,1647.83,1935.800,NaN,2158.980,NaN,1242.870,-2646.050,...,1660.650,-116.801,-568.05,-1357.140,553.286190,-2646.050,2158.980,4805.030,1630.962942,water
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,1207.7000,984.620,NaN,1166.25,937.478,1072.700,823.896,943.698,944.619,1040.990,...,362.882,979.795,NaN,433.659,922.351818,362.882,1589.000,1226.118,350.790091,impervious
7996,2170.3500,1419.720,1361.000,1478.71,983.911,1262.110,1422.860,1401.970,1372.680,1142.340,...,446.724,771.747,1589.06,506.936,1248.993808,336.289,2178.670,1842.381,581.812494,impervious
7997,1895.6800,1454.740,NaN,1033.56,1930.380,1057.150,1471.600,NaN,2693.630,2377.550,...,1095.000,1818.650,2501.72,1247.770,1563.116917,447.868,2780.930,2333.062,685.591736,impervious
7998,3465.7400,1283.320,413.412,4391.05,1146.820,4473.050,1614.750,770.469,NaN,2676.000,...,NaN,3759.710,NaN,388.346,2318.030304,244.594,5833.760,5589.166,1879.221363,impervious
7999,6941.1900,1667.870,5084.780,NaN,1588.950,5978.190,NaN,3068.030,6471.470,7150.420,...,NaN,5983.130,1249.71,2424.230,4215.831905,1249.710,7352.570,6102.860,2192.210975,impervious

In [5]:
df["class"].value_counts()#multiclass

class
forest        6159
farm           841
impervious     669
grass          196
water          105
orchard         30
Name: count, dtype: int64

In [6]:
df.isnull().sum()

20150720_N     560
20150602_N    1200
20150517_N     800
20150501_N     960
20150415_N     480
20150330_N    1120
20150314_N     720
20150226_N    1360
20150210_N     640
20150125_N    1040
20150109_N     880
20141117_N    1280
20141101_N     400
20141016_N    1440
20140930_N     800
20140813_N     560
20140626_N    1600
20140610_N     480
20140525_N     720
20140509_N     880
20140423_N    1760
20140407_N     640
20140322_N    1120
20140218_N    1440
20140202_N     560
20140117_N    1200
20140101_N     400
mean_ndvi        0
min_ndvi         0
max_ndvi         0
range_ndvi       0
std_ndvi         0
class            0
dtype: int64

In [7]:
#df.fillna(df.mean(numeric_only=True), inplace=True) #simple mean imputation [This part has a lot of scope for imporovement.]
#keep in mind that the data is inherently noisy and the test dataset is not.
#df.isnull().sum()

In [8]:
from sklearn.impute import KNNImputer
df.drop(columns=['Unnamed: 0', 'ID'], inplace=True, errors='ignore')


# Step 2: Separate target
target = df['class']
features = df.drop(columns=['class'])

# Step 3: Apply KNN imputer
imputer = KNNImputer(n_neighbors=5, weights='distance')  # Euclidean by default
features_imputed = imputer.fit_transform(features)

# Step 4: Reconstruct DataFrame
features_imputed_df = pd.DataFrame(features_imputed, columns=features.columns)
features_imputed_df['class'] = target
df=features_imputed_df
print("Null values remaining:", df.isnull().sum().sum())

Null values remaining: 0

In [9]:
df.isnull().sum()

20150720_N    0
20150602_N    0
20150517_N    0
20150501_N    0
20150415_N    0
20150330_N    0
20150314_N    0
20150226_N    0
20150210_N    0
20150125_N    0
20150109_N    0
20141117_N    0
20141101_N    0
20141016_N    0
20140930_N    0
20140813_N    0
20140626_N    0
20140610_N    0
20140525_N    0
20140509_N    0
20140423_N    0
20140407_N    0
20140322_N    0
20140218_N    0
20140202_N    0
20140117_N    0
20140101_N    0
mean_ndvi     0
min_ndvi      0
max_ndvi      0
range_ndvi    0
std_ndvi      0
class         0
dtype: int64

In [10]:
#to convert catogorical to numerical 
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['class'] = label_encoder.fit_transform(df['class'])

In [11]:
df

,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,20150125_N,...,20140218_N,20140202_N,20140117_N,20140101_N,mean_ndvi,min_ndvi,max_ndvi,range_ndvi,std_ndvi,class
0,637.5950,658.668000,-1882.030000,-1924.36000,997.904000,-1739.990000,630.087000,-312.766169,-1325.640000,-944.084000,...,211.328000,-2203.020,-1180.190000,433.906,-356.566818,-2203.020,997.904,3200.924,1310.703890,5
1,634.2400,593.705000,-1625.790000,-1672.32000,914.198000,-692.386000,707.626000,-1670.590000,-1408.640000,-989.285000,...,220.878000,-2250.000,-1360.560000,524.075,-252.624381,-2250.000,914.198,3164.198,1167.751946,5
2,58.0174,-1599.160000,-225.657270,-1052.63000,499.969614,-1564.630000,-976.088657,729.790000,-3162.140000,-1105.760525,...,369.214000,-2202.120,253.418159,-1343.550,-511.704400,-3162.140,952.178,4114.318,1569.573503,5
3,72.5180,-1213.847117,380.436000,-1256.93000,515.805000,-1413.180000,-802.942000,683.254000,-2829.400000,-1267.540000,...,298.320000,-2197.360,-100.928297,-826.727,-290.295917,-2829.400,1232.120,4061.520,1398.797808,5
4,1136.4400,1528.535900,-335.212980,1647.83000,1935.800000,597.763612,2158.980000,-798.425002,1242.870000,-2646.050000,...,1660.650000,-116.801,-568.050000,-1357.140,553.286190,-2646.050,2158.980,4805.030,1630.962942,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,1207.7000,984.620000,1004.356621,1166.25000,937.478000,1072.700000,823.896000,943.698000,944.619000,1040.990000,...,362.882000,979.795,647.873995,433.659,922.351818,362.882,1589.000,1226.118,350.790091,3
7996,2170.3500,1419.720000,1361.000000,1478.71000,983.911000,1262.110000,1422.860000,1401.970000,1372.680000,1142.340000,...,446.724000,771.747,1589.060000,506.936,1248.993808,336.289,2178.670,1842.381,581.812494,3
7997,1895.6800,1454.740000,1460.388546,1033.56000,1930.380000,1057.150000,1471.600000,1687.808648,2693.630000,2377.550000,...,1095.000000,1818.650,2501.720000,1247.770,1563.116917,447.868,2780.930,2333.062,685.591736,3
7998,3465.7400,1283.320000,413.412000,4391.05000,1146.820000,4473.050000,1614.750000,770.469000,3574.921555,2676.000000,...,291.436806,3759.710,2236.610248,388.346,2318.030304,244.594,5833.760,5589.166,1879.221363,3
7999,6941.1900,1667.870000,5084.780000,4582.44329,1588.950000,5978.190000,4308.778780,3068.030000,6471.470000,7150.420000,...,2587.287590,5983.130,1249.710000,2424.230,4215.831905,1249.710,7352.570,6102.860,2192.210975,3

In [12]:
#to split dataset 
#x -features , y=target
X = features_imputed_df.drop(columns=['class'])
y = features_imputed_df['class']

In [13]:
X

,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,20150125_N,...,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N,mean_ndvi,min_ndvi,max_ndvi,range_ndvi,std_ndvi
0,637.5950,658.668000,-1882.030000,-1924.36000,997.904000,-1739.990000,630.087000,-312.766169,-1325.640000,-944.084000,...,386.911507,211.328000,-2203.020,-1180.190000,433.906,-356.566818,-2203.020,997.904,3200.924,1310.703890
1,634.2400,593.705000,-1625.790000,-1672.32000,914.198000,-692.386000,707.626000,-1670.590000,-1408.640000,-989.285000,...,476.972000,220.878000,-2250.000,-1360.560000,524.075,-252.624381,-2250.000,914.198,3164.198,1167.751946
2,58.0174,-1599.160000,-225.657270,-1052.63000,499.969614,-1564.630000,-976.088657,729.790000,-3162.140000,-1105.760525,...,307.134734,369.214000,-2202.120,253.418159,-1343.550,-511.704400,-3162.140,952.178,4114.318,1569.573503
3,72.5180,-1213.847117,380.436000,-1256.93000,515.805000,-1413.180000,-802.942000,683.254000,-2829.400000,-1267.540000,...,282.833000,298.320000,-2197.360,-100.928297,-826.727,-290.295917,-2829.400,1232.120,4061.520,1398.797808
4,1136.4400,1528.535900,-335.212980,1647.83000,1935.800000,597.763612,2158.980000,-798.425002,1242.870000,-2646.050000,...,1020.720000,1660.650000,-116.801,-568.050000,-1357.140,553.286190,-2646.050,2158.980,4805.030,1630.962942
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,1207.7000,984.620000,1004.356621,1166.25000,937.478000,1072.700000,823.896000,943.698000,944.619000,1040.990000,...,465.843000,362.882000,979.795,647.873995,433.659,922.351818,362.882,1589.000,1226.118,350.790091
7996,2170.3500,1419.720000,1361.000000,1478.71000,983.911000,1262.110000,1422.860000,1401.970000,1372.680000,1142.340000,...,485.204000,446.724000,771.747,1589.060000,506.936,1248.993808,336.289,2178.670,1842.381,581.812494
7997,1895.6800,1454.740000,1460.388546,1033.56000,1930.380000,1057.150000,1471.600000,1687.808648,2693.630000,2377.550000,...,1170.880000,1095.000000,1818.650,2501.720000,1247.770,1563.116917,447.868,2780.930,2333.062,685.591736
7998,3465.7400,1283.320000,413.412000,4391.05000,1146.820000,4473.050000,1614.750000,770.469000,3574.921555,2676.000000,...,744.143000,291.436806,3759.710,2236.610248,388.346,2318.030304,244.594,5833.760,5589.166,1879.221363
7999,6941.1900,1667.870000,5084.780000,4582.44329,1588.950000,5978.190000,4308.778780,3068.030000,6471.470000,7150.420000,...,5299.900000,2587.287590,5983.130,1249.710000,2424.230,4215.831905,1249.710,7352.570,6102.860,2192.210975

In [14]:
y

0       5
1       5
2       5
3       5
4       5
       ..
7995    3
7996    3
7997    3
7998    3
7999    3
Name: class, Length: 8000, dtype: int32

In [15]:

from sklearn.model_selection import train_test_split
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
classifier = LogisticRegression(    multi_class='multinomial',solver='lbfgs', max_iter=10)
classifier.fit(X_train, y_train)

c:\Users\Lenovo\anaconda3\envs\myenv\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Lenovo\anaconda3\envs\myenv\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=10, multi_class='multinomial')

In [17]:
# Predict on test set
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
print(classification_report(y_test, y_pred,labels=list(range(len(label_encoder.classes_))),
    target_names=label_encoder.classes_))

              precision    recall  f1-score   support

        farm       0.54      0.38      0.44       168
      forest       0.84      0.97      0.90      1232
       grass       0.00      0.00      0.00        39
  impervious       0.88      0.32      0.47       134
     orchard       0.00      0.00      0.00         6
       water       1.00      0.10      0.17        21

    accuracy                           0.82      1600
   macro avg       0.54      0.29      0.33      1600
weighted avg       0.79      0.82      0.78      1600

c:\Users\Lenovo\anaconda3\envs\myenv\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Lenovo\anaconda3\envs\myenv\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Lenovo\anaconda3\envs\myenv\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [18]:
test_data = pd.read_csv("C:/Users/Lenovo/Desktop/IITG (summer analytics)/hackathon/hacktest.csv")

print("Columns in test_data:", test_data.columns.tolist())

Columns in test_data: ['Unnamed: 0', 'ID', '20150720_N', '20150602_N', '20150517_N', '20150501_N', '20150415_N', '20150330_N', '20150314_N', '20150226_N', '20150210_N', '20150125_N', '20150109_N', '20141117_N', '20141101_N', '20141016_N', '20140930_N', '20140813_N', '20140626_N', '20140610_N', '20140525_N', '20140509_N', '20140423_N', '20140407_N', '20140322_N', '20140218_N', '20140202_N', '20140117_N', '20140101_N']

In [19]:
ID=test_data['ID']
test_data.drop(columns=['Unnamed: 0', 'ID'], inplace=True, errors='ignore')

In [20]:
ndvi_cols = [col for col in test_data.columns if "_N" in col]
test_data['mean_ndvi'] = test_data[ndvi_cols].mean(axis=1)
test_data['min_ndvi'] = test_data[ndvi_cols].min(axis=1)
test_data['max_ndvi'] = test_data[ndvi_cols].max(axis=1)
test_data['range_ndvi'] = test_data['max_ndvi'] - test_data['min_ndvi']
test_data['std_ndvi'] = test_data[ndvi_cols].std(axis=1)

In [21]:
y_test = classifier.predict(test_data)

In [22]:
y_test

array([1, 1, 1, ..., 5, 5, 5])

In [23]:
#convert back to classifer 
y_decoded = label_encoder.inverse_transform(y_test)
y_decoded

array(['forest', 'forest', 'forest', ..., 'water', 'water', 'water'],
      dtype=object)

In [24]:
result = pd.DataFrame({
    'ID': ID,
    'class': y_decoded
})

In [25]:
result

        ID   class
0        1  forest
1        2  forest
2        3  forest
3        4  forest
4        5  forest
...    ...     ...
2840  2841   water
2841  2842   water
2842  2843   water
2843  2844   water
2844  2845   water

[2845 rows x 2 columns]

In [26]:

result.to_csv("hackathon.csv", index=False)